### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by GianlucaGuarini** [jimsparkman/RiotControl#1] opened 2015-01-28 08:33 UTC
Anytime a todo entry gets removed the following event does not get removed with it:

``` javascript
RiotControl.on('todos_changed', function(items) {
    self.items = items
    self.update()
})
```

I have created a simple demo to demonstrate this http://jsfiddle.net/gianlucaguarini/kmLr3hbj/
Just click on 'add' and 'remove' to see your browser heap snapshots growing
![screen shot 2015-01-28 at 09 30 36](https://cloud.githubusercontent.com/assets/879612/5934505/aa40e518-a6d0-11e4-8190-1512ac98c2f6.png)

**Comment by jimsparkman** [comment] 2015-01-28 23:48
RiotControl.on feeds into riot.on. You've traced it to eventing? If I remove all eventing, RiotControl and riot's observable, and just add remove 500 items from the tag's this.items the heap grows regardless.

**Comment by jimsparkman** [comment] 2015-01-29 02:07
Also: https://github.com/muut/riotjs/issues/248

**Comment by rsbondi** [comment] 2015-01-29 03:10
I have tested the multi todo example following the approach in #248 and I get the same thing, all objects persist so it appears to be with riot and not RiotControl

**Comment by jimsparkman** [comment] 2015-01-30 23:18
Looks like @rsbondi is working on this.

https://github.com/muut/riotjs/pull/260

**Comment by jimsparkman** [comment] 2015-02-05 23:58
Closing: The issue is being worked on in riotjs.

**Closed as completed by jimsparkman** 2015-02-05 23:58 UTC

**Comment by GianlucaGuarini** [comment] 2015-02-09 22:33
I am sorry but the problem is still there even with the newest riot release, you just need to run the demo http://jsfiddle.net/gianlucaguarini/kmLr3hbj/ already linked

![screen shot 2015-02-09 at 23 30 52](https://cloud.githubusercontent.com/assets/879612/6117307/d15e49aa-b0b3-11e4-8928-6c302fdf3241.png)

**Comment by tipiirai** [comment] 2015-02-10 07:41
Can you post this issue to Riot repository: https://github.com/muut/riotjs/issues

Thank you!

**Comment by tipiirai** [comment] 2015-02-10 07:43
Ignore above! It's already there: https://github.com/muut/riotjs/issues/248
